### ISSUE TITLE
Another way to run this without Eclipse?

### ISSUE THREAD

**Issue by ghost** [admazzola/JavaNESBrain#4]
It would be nice, because I would love to see it, but I don't want to install Eclipse at the moment.

**Comment by ethereumdegen** [comment]
Yes, you can totally run it in any IDE or build it yourself.  I just mentioned 'eclipse' because the eclipse .project file is already there in the repo.

**Comment by ghost** [comment]
@admazzola Thanks! Can you let me know the `build` instructions?

**Comment by ethereumdegen** [comment]
Just add the 'json simple' jar from the 'lib' folder to your build path.
The latest commit actually doesn't even require that.  basically just
compile it and run the main function of 'SuperBrain'

**Comment by ghost** [comment]
@admazzola Got it! Awesome and thanks.
