### ISSUE TITLE
What main class?

### ISSUE THREAD

**Issue by aodhan1** [admazzola/JavaNESBrain#7]
Can't find an entry point for NN program? The only main class seems to be located in ./JavaNESBrain/src/jp/tanakh/bjne/ui/BJNEmulator.java

**Comment by ethereumdegen** [comment]
all good ?

**Comment by ethereumdegen** [comment]
I think its https://github.com/admazzola/JavaNESBrain/blob/master/JavaNESBrain/src/com/starflask/JavaNESBrain/SuperBrain.java  but this is an ooold repo ^^
